name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  linter:
    name: 'Linter'
    uses: ./.github/workflows/template-linter.yaml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  template_validation:
    name: 'Template Validation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check File Case in .github/**
        shell: pwsh
        run: |
          $errors = 0

          Get-ChildItem -Path . -Recurse -File -Force | ForEach-Object {
              $fileName = $_.Name

              if ($fileName -notlike '*PULL_REQUEST_TEMPLATE*' -and $fileName -cne $fileName.ToLowerInvariant()) {
                  Write-Output "🚫 File not lowercase: $($_.FullName)"
                  $errors++
              }
          }

          if ($errors -ne 0) {
              Write-Output "❌ Found $errors file(s) with uppercase letters."
              exit 1
          }

          Write-Output '✅ All filenames are lowercase.'
        working-directory: .github

      - name: Check File Patterns in .github/**
        shell: pwsh
        run: |
          $errors = 0
          $allowedPatterns = @(
              'action.yml'
              '*.yaml'
              '.*'
              'template-*'
              'workflow-*'
              '*.md'
          )

          Get-ChildItem -Path . -Recurse -File -Force | ForEach-Object {
              $fileName = $_.Name
              $isValid = $allowedPatterns.Where({ $fileName -like $_ }).Count -gt 0

              if ($isValid) {
                  Write-Output "✅ Valid filename pattern: $($_.FullName)"
              }
              else {
                  Write-Output "🚫 Invalid filename pattern: $($_.FullName)"
                  $errors++
              }
          }

          if ($errors -gt 0) {
              Write-Output "❌ Found $errors file(s) that don't match allowed patterns."
              exit 1
          }

          Write-Output '✅ All filenames match allowed patterns.'
        working-directory: .github

      - name: Check Examples
        shell: pwsh
        run: |
          $errors = 0
          $workflowFiles = Get-ChildItem -Path $env:WORKFLOWS_DIR -File | Where-Object {
              $_.Name -like 'template-*.yaml' -or $_.Name -like 'workflow-*.yaml'
          }

          foreach ($file in $workflowFiles) {
              Write-Output "⚙️ Processing file : $($file.FullName)"

              if ($file.BaseName -like 'workflow-*') {
                  $exampleFile = Join-Path $env:WORKFLOWS_EXAMPLES_DIR "$($file.BaseName).md"
              }
              else {
                  $exampleFile = Join-Path $env:TEMPLATES_EXAMPLES_DIR "$($file.BaseName).md"
              }

              if (Test-Path -LiteralPath $exampleFile -PathType Leaf) {
                  Write-Output "✅ Example file found : $exampleFile"
              }
              else {
                  Write-Output "🚫 Example file not found : $exampleFile"
                  $errors++
              }
          }

          if (Test-Path -LiteralPath $env:ACTIONS_DIR -PathType Container) {
              foreach ($folder in Get-ChildItem -Path $env:ACTIONS_DIR -Directory) {
                  Write-Output "📁 Processing folder : $($folder.FullName)"
                  $exampleFile = Join-Path $env:ACTIONS_EXAMPLES_DIR "$($folder.Name).md"

                  if (Test-Path -LiteralPath $exampleFile -PathType Leaf) {
                      Write-Output "✅ Example file found : $exampleFile"
                  }
                  else {
                      Write-Output "🚫 Example file not found : $exampleFile"
                      $errors++
                  }
              }
          }

          if ($errors -gt 0) {
              Write-Output "❌ Found $errors templates that require example files."
              exit 1
          }

          Write-Output '✅ All templates have example files!'
        env:
          WORKFLOWS_DIR: .github/workflows
          WORKFLOWS_EXAMPLES_DIR: examples/workflows
          TEMPLATES_EXAMPLES_DIR: examples/templates
          ACTIONS_DIR: .github/actions
          ACTIONS_EXAMPLES_DIR: examples/actions

  conventional_commits:
    name: 'Validate Commits'
    uses: ./.github/workflows/template-conventional-commits.yaml

  git_versioning:
    name: 'Preview Git Versioning'
    uses: ./.github/workflows/template-git-versioning.yaml
    with:
      dry_run: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
