on:
  workflow_call:
    inputs:
      runs_on:
        default: ubuntu-latest
        required: false
        type: string
      lint_terraform:
        default: false
        required: false
        type: boolean
    secrets:
      gh_token:
        required: true

jobs:
  linter:
    name: 'SuperLinter'
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Run Super-Linter'
        uses: super-linter/super-linter/slim@v8.1.0
        env:
          CREATE_LOG_FILE: true
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          LINTER_RULES_PATH: .github/linters
          PRETTIER_COMMAND_OPTIONS: '--config .github/linters/.prettierrc.json'
          VALIDATE_ARM: true
          VALIDATE_BASH: true
          VALIDATE_CHECKOV: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_POWERSHELL: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML_PRETTIER: true

      - name: 'Copy Super-Linter Job Summary'
        run: |
          DIR="/home/runner/work/_temp/_runner_file_commands"

          find "$DIR" -type f -name 'step_summary_*scrubbed' | while read -r file; do
            if grep -q "Super-linter" "$file"; then
              echo "Copying Super-Linter job summary."
              cp "$file" "$GITHUB_WORKSPACE/super-linter-summary.md"
            fi
          done
        if: always()

      - name: 'Add Pull Request Comment'
        if: always() && github.event_name == 'pull_request'
        shell: pwsh
        run: |
          $ghToken         = "${{ secrets.GITHUB_TOKEN }}"
          $repositoryName  = ("${{ github.repository }}" -Split '/')[1]
          $repositoryOwner = ("${{ github.repository }}" -Split '/')[0]
          $issueNumber     = "${{ github.event.pull_request.number }}"
          $commentSearch   = "# Super-linter summary"
          $bodyContent     = Get-Content "${{ github.workspace }}/super-linter-summary.md" -Raw

          $apiHeaders = @{
            Authorization = "Bearer $ghToken"
            Accept = "application/vnd.github.v3+json"
          }

          # Get existing comments and search for commentSearch value.
          $commentsUri      = "https://api.github.com/repos/$repositoryOwner/$repositoryName/issues/$issueNumber/comments"
          $existingComments = Invoke-RestMethod -Uri $commentsUri -Headers $apiHeaders
          $existingComment  = $existingComments | Where-Object { $_.body -like "*$commentSearch*" }

          # Delete existing comment if found, then create new comment.
          if ($existingComment) {
              Write-Output "Deleting existing comment."
              $deleteUri     = "https://api.github.com/repos/$repositoryOwner/$repositoryName/issues/comments/$($existingComment.id)"
              $deleteComment = Invoke-RestMethod -Method Delete -Uri $deleteUri -Headers $apiHeaders
          }

          Write-Output "Creating new comment."
          $createUri     = "https://api.github.com/repos/$repositoryOwner/$repositoryName/issues/$issueNumber/comments"
          $createComment = Invoke-RestMethod -Method Post -Uri $createUri -Headers $apiHeaders -Body (@{ body = $bodyContent } | ConvertTo-Json -Depth 2)
